default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  #socket: /tmp/mysql.sock

development:
  <<: *default
  database: dozer_services_development

test:
  <<: *default
  database: dozer_services_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: dozer_services_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
